version: '3'

services:

  reverse-proxy:
    image: traefik 
    command: --api --docker
    ports:
      - "80:80"     
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - locationapi
      - purchasesapi

  broker:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./services/broker/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    labels:
      - "traefik.enable=false"
    
  mongodb:
    image: mongo:3.4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./services/database/dbdata:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet 
    labels:
      - "traefik.enable=false"
    
  locationapi:
    build: services/location-api/
    working_dir: /src
    command: bash -c "npm install && npm run deploy"
    volumes:
      - ./services/location-api/location:/src
    # ports:
    #   - "3002:3000"        
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_SERVICE=mongodb:27017/ratings_management_location_db
      - AMQP_SERVICE=broker:5672
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:backend.localhost;PathPrefixStrip:/location"        
    links:
      - mongodb
    depends_on:
      - mongodb

  purchasesapi:
    build: services/purchases-api/
    working_dir: /src
    command: bash -c "npm install && npm run deploy"
    volumes:
      - ./services/purchases-api/purchases:/src
    # ports:
    #   - "3001:3000"        
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_SERVICE=mongodb:27017/ratings_management_purchases_db"
      - AMQP_SERVICE=broker
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:backend.localhost;PathPrefixStrip:/purchases"        
    links:
      - mongodb
      - broker
    depends_on:
      - mongodb
      - broker

  usersapi:
    build: services/users-api/
    working_dir: /src
    command: bash -c "npm install && npm run deploy"
    volumes:
      - ./services/users-api/users:/src
    # ports:
    #   - "3001:3000"        
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_SERVICE=mongodb:27017/local"
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:backend.localhost;PathPrefixStrip:/users"        
    links:
      - mongodb
    depends_on:
      - mongodb
